server.port: 8913

spring:
  data:
    couchbase:
      couchbaseHost: ${couchbaseHost:localhost}
      couchbaseBucket: ${couchbaseBucket:Administrator}
      couchbaseBucketPassword: ${couchbaseBucketPassword:123456}