server.port: 8913

spring:
  data:
    couchbase:
      couchbaseHost: ${COUCHBASE_HOST:localhost}
      couchbaseBucket: ${COUCHBASE_BUCKET:travel-sample}
      couchbaseBucketPassword: ${couchbaseBucketPassword:}